name: "Download File with Caching"
description: Downloads an individual file from a URL or loads it from a cache

inputs:
  url:
    description: URL of the file to download
    required: true
  destination:
    description: Path to write the downloaded file to, or to load the cached file from
    required: true
  cache-key:
    description: An explicit key for a cache entry
    required: false

outputs:
  destination:
    description: Path of the downloaded file
    value: ${{inputs.destination}}

runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_DESTINATION: ${{inputs.destination}}
      run: |
        parent_dir="$(dirname "$INPUT_DESTINATION")"
        if ! mkdir -p "$parent_dir"; then
          sudo mkdir -p "$parent_dir"
          sudo chown "$USER" "$parent_dir"
        fi

    - uses: actions/cache/restore@v4
      id: restore_cache
      with:
        path: ${{inputs.destination}}
        key: ${{inputs.cache-key || inputs.url}}

    - shell: bash
      if: ${{!steps.restore_cache.outputs.cache-hit}}
      env:
        INPUT_URL: ${{inputs.url}}
        INPUT_DESTINATION: ${{inputs.destination}}
      run: |
        echo "Downloading $INPUT_URL to $INPUT_DESTINATION..."
        curl -L -o "$INPUT_DESTINATION" "$INPUT_URL"

    - uses: actions/cache/save@v4
      if: ${{!steps.restore_cache.outputs.cache-hit}}
      with:
        path: ${{inputs.destination}}
        key: ${{inputs.cache-key || inputs.url}}
