//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OBSNotifier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OBSNotifier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OK] Fetching project info
        ///Translated:
        ///	- af: 0%
        ///	- ar: 78%
        ///	- ca: 0%
        ///	- cs: 98%
        ///	- da: 98%
        ///	- de: 98%
        ///	- el: 79%
        ///	- es-ES: 86%
        ///	- fi: 98%
        ///	- fr: 86%
        ///	- he: 0%
        ///	- hu: 0%
        ///	- it: 98%
        ///	- ja: 84%
        ///	- ko: 0%
        ///	- nl: 86%
        ///	- no: 86%
        ///	- pl: 86%
        ///	- pt-BR: 93%
        ///	- pt-PT: 93%
        ///	- ro: 98%
        ///	- ru: 99%
        ///	- sr: 0%
        ///	- sv-SE: 98%
        ///	- tr: 0%
        ///	- vi: 0%
        ///	- zh-CN: 75%
        ///	- zh-TW: 0%
        ///Approved:
        ///	- af: 0%
        ///	- ar: 0%
        ///	- ca: 0%
        ///	- cs: 0%
        ///	- da: 0%
        ///	- de: 0%
        ///	- el: 0%
        ///	- es-ES: 0%
        ///	- fi: 0%
        ///	- fr: 0%
        ///	- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string localization_status {
            get {
                return ResourceManager.GetString("localization_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obs_notifier {
            get {
                object obj = ResourceManager.GetObject("obs_notifier", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon obs_notifier_64px {
            get {
                object obj = ResourceManager.GetObject("obs_notifier_64px", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --[[
        ///	The original code was written by xcasxcursex
        ///	https://github.com/DmitriySalnikov/OBSNotifier/issues/5
        ///--]]
        ///
        ///obs = obslua
        ///
        ///-- WinAPI
        ///-- https://stackoverflow.com/a/61269226/8980874
        ///local ffi = require(&quot;ffi&quot;)
        ///local bit32 = require(&quot;bit&quot;)
        ///local BELOW_NORMAL_PRIORITY_CLASS = 0x00004000
        ///local NORMAL_PRIORITY_CLASS = 0x00000020
        ///local CREATE_NEW_PROCESS_GROUP = 0x00000200
        ///
        ///ffi.cdef [[ typedef struct _STARTUPINFOW { uint32_t cb; void * lpReserved; void * lpDesktop; void * lpTitle; uint32_t dwX; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string obs_notifier_autostart {
            get {
                return ResourceManager.GetString("obs_notifier_autostart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon obs_notifier_connected_64px {
            get {
                object obj = ResourceManager.GetObject("obs_notifier_connected_64px", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon obs_notifier_reconnect_64px {
            get {
                object obj = ResourceManager.GetObject("obs_notifier_reconnect_64px", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
