name: ↗️ Update translations from the community
run-name: "Update on '${{github.ref_name}}' '${{github.sha}}' #${{github.run_number}}"

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  update:
    name: Update Translations
    runs-on: ubuntu-latest

    env:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          lfs: true
      
      - name: Crowdin Install
        run: |
          wget https://artifacts.crowdin.com/repo/deb/crowdin3.deb -O ../crowdin.deb
          sudo dpkg -i ../crowdin.deb
      
      - name: Crowdin Download
        run: |
          crowdin pull --no-progress
      
      - name: Crowdin Status to file
        run: |
          crowdin status --no-progress > OBSNotifier/Localization/localization_status.txt
      
      - name: Commit report
        run: |
          git config --global user.name 'Auto Updater'
          git config --global user.email 'auto-updater@users.noreply.github.com'
          git diff
          echo "# Changed files:" >> $GITHUB_STEP_SUMMARY
          git diff --name-only >> $GITHUB_STEP_SUMMARY
          git add -A
          git commit -am "[CI] ↗️ Updated Localization"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          branch: ${{ github.ref }}